# -*- coding: utf-8 -*-
"""text_to_sign_language_converter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1shM6El61zn6bOSBEvWZ_ZQPAJZRIveXZ
"""

import kagglehub
datamunge_sign_language_mnist_path = kagglehub.dataset_download('datamunge/sign-language-mnist')
prathumarikeri_indian_sign_language_isl_path = kagglehub.dataset_download('prathumarikeri/indian-sign-language-isl')
rayeed045_american_sign_language_digit_dataset_path = kagglehub.dataset_download('rayeed045/american-sign-language-digit-dataset')

print('Data source import complete.')

"""### We will take a look at 2 sign languages in this notebook
##### ```1. Digit```
##### ```2. ISL (Indian Sign Language)```

# Importing Essential Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from PIL import Image

import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import confusion_matrix

import warnings
# Ignore warnings
warnings.filterwarnings("ignore")

"""# Loading the Digit's DataSet"""

root_dir = os.path.join(rayeed045_american_sign_language_digit_dataset_path, 'American Sign Language Digits Dataset')

image_data = []

for label in range(10):
    label_dir = os.path.join(root_dir, str(label), 'Input Images - Sign {}'.format(label))
    for image_file in os.listdir(label_dir):
        image = Image.open(os.path.join(label_dir, image_file))
        image_data.append({
            'label': label,
            'color_image': image
        })

df = pd.DataFrame(image_data)

df

"""# Data Visualization (EDA)"""

plt.figure(figsize=(6, 6))
sns.set_style("darkgrid")
sns.countplot(data=df,x='label')

plt.xlabel('Label')
plt.ylabel('Count')
plt.title('Distribution of Labels')

plt.show()

fig, axs = plt.subplots(2, 5, figsize=(12, 6))

for i, (label, image) in enumerate(df.groupby('label').first().reset_index()[['label', 'color_image']].itertuples(index=False)):
    ax = axs[i // 5, i % 5]
    ax.imshow(image)
    ax.set_title('Label {}'.format(label))
    ax.axis('off')

plt.axis('off')
plt.tight_layout()
plt.show()

"""# Data Preprocessing"""

# Preprocessing steps
images = np.array(df['color_image'].tolist())
labels = np.array(df['label'])

# Resize images to desired dimensions and convert to numpy arrays
resized_images_np = []
for pil_image in df['color_image']:
    # Ensure image is in RGB format before resizing and converting to numpy
    if pil_image.mode != 'RGB':
        pil_image = pil_image.convert('RGB')
    resized_pil_image = pil_image.resize((32, 32))  # Resize the PIL Image
    resized_images_np.append(np.array(resized_pil_image)) # Convert to NumPy array
images = np.array(resized_images_np) # Stack all NumPy arrays into a single array

# Normalize pixel values
images = images / 255.0

"""# Splitting the Data into Train Test Split"""

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

# Convert labels to categorical format
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

"""# Model Architecture"""

model = Sequential()
model.add(Conv2D(75, (3, 3), strides=1, padding='same', activation='relu', input_shape=(32, 32, 3)))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2), strides=2, padding='same'))
model.add(Conv2D(50, (3, 3), strides=1, padding='same', activation='relu'))
model.add(Dropout(0.2))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2), strides=2, padding='same'))
model.add(Conv2D(25, (3, 3), strides=1, padding='same', activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2), strides=2, padding='same'))
model.add(Flatten())
model.add(Dense(units=512, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='SGD', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

"""# Data Augmentation"""

datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        rotation_range=10,  # randomly rotate images in the range (degrees, 0 to 180)
        zoom_range = 0.1, # Randomly zoom image
        width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=False,  # randomly flip images
        vertical_flip=False)  # randomly flip images

datagen.fit(X_train)

"""# Fitting of the Model"""

learning_rate_reduction = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_acc', patience=2, verbose=1, factor=0.5, min_lr=0.0001)
history = model.fit(datagen.flow(X_train, y_train), epochs=30, validation_data=(X_test, y_test), callbacks=[learning_rate_reduction])

"""# Model Evaluation"""

# Create subplots
fig, axs = plt.subplots(1, 2, figsize=(12, 4))

# Define plot labels and styles
plot_labels = ['Accuracy', 'Loss']
plot_styles = ['-', '--']

# Plot training and testing accuracy/loss
for i, metric in enumerate(['accuracy', 'loss']):
    train_metric = history.history[metric]
    test_metric = history.history['val_' + metric]
    axs[i].plot(train_metric, label='Training ' + metric.capitalize(), linestyle=plot_styles[0])
    axs[i].plot(test_metric, label='Testing ' + metric.capitalize(), linestyle=plot_styles[1])
    axs[i].set_xlabel('Epochs')
    axs[i].set_ylabel(plot_labels[i])
    axs[i].legend()

# Adjust layout and display the plot
plt.tight_layout()
plt.show()

# Get the model's predictions on the test set
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true_classes = np.argmax(y_test, axis=1)

# Create the confusion matrix
cm = confusion_matrix(y_true_classes, y_pred_classes)

# Visualize the confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, cmap='Blues', fmt='d')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

accuracy = model.evaluate(X_test, y_test)
print(f'validation test results - Loss: {accuracy[0]} - Accuracy: {accuracy[1]*100}%')

"""# Saving the Model"""

model.save("digitSignLanguage.h5")

"""# <center> -----------------------------  END   ---------------------------</center>

# <center> -----------------------------  Start ISL   ---------------------------</center>

# Loading Datast
"""

# Define the root directory path
root_dir = os.path.join(prathumarikeri_indian_sign_language_isl_path, 'Indian')

# Maximum number of images to load from each subdir_path
max_images_per_subdir = 500

# Initialize a list to store the image data
image_data = []

# Iterate through the subdirectories in the root directory
for label_folder_name in os.listdir(root_dir):
    # Check if the subdirectory is numeric or a specific label name
    # Assuming labels are folders like 'A', 'B', 'C', etc.
    subdir_path = os.path.join(root_dir, label_folder_name)

    if os.path.isdir(subdir_path):
        # Use list comprehension to load a maximum images
        images = []
        for i, file in enumerate(os.listdir(subdir_path)):
            if i >= max_images_per_subdir:
                break
            # Check if the file is an image
            if file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
                images.append({
                    'label': label_folder_name, # Use folder name as label
                    'color_image': Image.open(os.path.join(subdir_path, file))
                })
        # Extend the image_data list with the loaded images
        image_data.extend(images)

# Create a DataFrame from the image data
df = pd.DataFrame(image_data)

df

df['label'].unique()

"""# Data Visualization (EDA)"""

plt.figure(figsize=(10, 5))
sns.set_style("darkgrid")
sns.countplot(data=df,x='label')

plt.xlabel('Label')
plt.ylabel('Count')
plt.title('Distribution of Labels')

plt.show()

fig, axs = plt.subplots(3,13, figsize=(18, 6)) # Increased rows from 2 to 3 and adjusted figsize for better layout

for i, (label, image) in enumerate(df.groupby('label').first().reset_index()[['label', 'color_image']].itertuples(index=False)):
    ax = axs[i // 13, i % 13]
    ax.imshow(image)
    ax.set_title('Label {}'.format(label))
    ax.axis('off')

# Hide any unused subplots
for i in range(len(df['label'].unique()), 3 * 13):
    axs.flatten()[i].axis('off')

plt.tight_layout()
plt.show()

"""# Data Preprocessing"""

# Preprocessing steps
resized_images_np = []
for pil_image in df['color_image']:
    # Ensure image is in RGB format before resizing and converting to numpy
    if pil_image.mode != 'RGB':
        pil_image = pil_image.convert('RGB')
    resized_pil_image = pil_image.resize((32, 32))  # Resize the PIL Image
    resized_images_np.append(np.array(resized_pil_image)) # Convert to NumPy array
images = np.array(resized_images_np) # Stack all NumPy arrays into a single array
labels = np.array(df['label'])

# The image resizing and conversion to numpy array is now handled in the previous cell.

# Normalize pixel values
images = images / 255.0

# Map labels to numerical values
label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(labels)

"""# Splitting the data into Training and Testing"""

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

# Convert labels to categorical format
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

"""# Model Architecture"""

model = Sequential()
model.add(Conv2D(75, (3, 3), strides=1, padding='same', activation='relu', input_shape=(32, 32, 3)))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2), strides=2, padding='same'))
model.add(Conv2D(50, (3, 3), strides=1, padding='same', activation='relu'))
model.add(Dropout(0.2))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2), strides=2, padding='same'))
model.add(Conv2D(25, (3, 3), strides=1, padding='same', activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2), strides=2, padding='same'))
model.add(Flatten())
model.add(Dense(units=512, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(units=35, activation='softmax'))

model.compile(optimizer='SGD', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

"""# Data Augmentation"""

datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        rotation_range=10,  # randomly rotate images in the range (degrees, 0 to 180)
        zoom_range = 0.1, # Randomly zoom image
        width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=False,  # randomly flip images
        vertical_flip=False)  # randomly flip images

datagen.fit(X_train)

"""# Fitting the Model"""

learning_rate_reduction = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_acc', patience=2, verbose=1, factor=0.5, min_lr=0.001)
history = model.fit(datagen.flow(X_train,y_train), epochs=25, validation_data=(X_test, y_test), callbacks=[learning_rate_reduction])

"""# Model Evaluation"""

# Create subplots
fig, axs = plt.subplots(1, 2, figsize=(12, 4))

# Define plot labels and styles
plot_labels = ['Accuracy', 'Loss']
plot_styles = ['-', '--']

# Plot training and testing accuracy/loss
for i, metric in enumerate(['accuracy', 'loss']):
    train_metric = history.history[metric]
    test_metric = history.history['val_' + metric]
    axs[i].plot(train_metric, label='Training ' + metric.capitalize(), linestyle=plot_styles[0])
    axs[i].plot(test_metric, label='Testing ' + metric.capitalize(), linestyle=plot_styles[1])
    axs[i].set_xlabel('Epochs')
    axs[i].set_ylabel(plot_labels[i])
    axs[i].legend()

# Adjust layout and display the plot
plt.tight_layout()
plt.show()

# Get the model's predictions on the test set
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true_classes = np.argmax(y_test, axis=1)

# Create the confusion matrix
cm = confusion_matrix(y_true_classes, y_pred_classes)

# Visualize the confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, cmap='Blues', fmt='d')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

accuracy = model.evaluate(X_test, y_test)
print(f'validation test results - Loss: {accuracy[0]} - Accuracy: {accuracy[1]*100}%')

"""# Saving the Model"""

model.save("indianSignLanguage.h5")

"""# Task
Create a text-to-sign language converter by preparing a comprehensive character-to-sign mapping from the "American Sign Language Digit dataset" and the "Indian Sign Language (ISL)" dataset. Prompt the user for text input, convert it to an image sequence using the mapping, and display the sign language output. Summarize the conversion with the input text and the displayed sign language.

## Prepare Character-to-Sign Mapping

### Subtask:
Load and process both the American Sign Language Digit dataset and the Indian Sign Language (ISL) dataset. Create a comprehensive mapping that links individual alphanumeric characters (0-9, A-Z) to their representative sign language images from these datasets.

**Reasoning**:
The subtask requires loading and processing the American Sign Language Digit dataset. Since the `df` variable currently holds the Indian Sign Language (ISL) data, I will reload the digit dataset into a new DataFrame named `df_digits` to prevent overwriting.
"""

root_dir_digits = os.path.join(rayeed045_american_sign_language_digit_dataset_path, 'American Sign Language Digits Dataset')

image_data_digits = []

for label in range(10):
    label_dir = os.path.join(root_dir_digits, str(label), 'Input Images - Sign {}'.format(label))
    for image_file in os.listdir(label_dir):
        image = Image.open(os.path.join(label_dir, image_file))
        image_data_digits.append({
            'label': str(label),
            'color_image': image
        })

df_digits = pd.DataFrame(image_data_digits)
print("American Sign Language Digit dataset loaded into df_digits.")

"""**Reasoning**:
I will initialize an empty dictionary `char_to_sign_map` and populate it with one representative image for each unique digit from `df_digits` (American Sign Language Digit dataset) and each unique character from `df` (Indian Sign Language dataset), resizing all images to 32x32 pixels to maintain uniformity.


"""

char_to_sign_map = {}

# Process American Sign Language Digit dataset (df_digits)
for label in df_digits['label'].unique():
    # Select the first image for each digit label
    representative_image = df_digits[df_digits['label'] == label]['color_image'].iloc[0]
    # Resize image to 32x32
    if representative_image.mode != 'RGB':
        representative_image = representative_image.convert('RGB')
    char_to_sign_map[label] = representative_image.resize((32, 32))

# Process Indian Sign Language (ISL) dataset (df)
for label in df['label'].unique():
    # Ensure label is uppercase for consistency
    upper_label = str(label).upper()
    # Only add if not already present from digits (in case ISL also has digits)
    if upper_label not in char_to_sign_map:
        # Select the first image for each character label
        representative_image = df[df['label'] == label]['color_image'].iloc[0]
        # Resize image to 32x32
        if representative_image.mode != 'RGB':
            representative_image = representative_image.convert('RGB')
        char_to_sign_map[upper_label] = representative_image.resize((32, 32))

print(f"Character-to-sign mapping created for {len(char_to_sign_map)} unique characters/digits.")

"""## Get User Text Input

### Subtask:
Prompt the user for text input and preprocess it to ensure it only contains characters for which a sign language image is available in the mapping.

**Reasoning**:
I will prompt the user for text input, convert it to uppercase, and then iterate through each character to build a `processed_text` string containing only characters that exist as keys in the `char_to_sign_map`.
"""

user_input_text = input("Enter the text you want to convert to sign language: ")
upper_input_text = user_input_text.upper()

processed_text = ""
for char in upper_input_text:
    if char in char_to_sign_map:
        processed_text += char

print(f"Original input: '{user_input_text}'")
print(f"Processed input for sign conversion: '{processed_text}'")

"""**Reasoning**:
Now that the input text has been processed and validated against the character-to-sign mapping, the next step is to retrieve and display the corresponding sign language images for each character in the `processed_text`.


"""

print("Converting your text to sign language:")

plt.figure(figsize=(2 * len(processed_text), 3))
for i, char in enumerate(processed_text):
    sign_image = char_to_sign_map[char]
    plt.subplot(1, len(processed_text), i + 1)
    plt.imshow(sign_image)
    plt.title(f"'{char}'")
    plt.axis('off')

plt.tight_layout()
plt.show()

"""### Sign Language Conversion Summary

**Original Input Text:** '{{user_input_text}}'

**Processed Text for Conversion:** '{{processed_text}}'

**Sign Language Display:** The images above represent the sign language for each character in the processed text, demonstrating the conversion from the input text to a visual sequence of signs.

### Sign Language Conversion Summary

**Original Input Text:** '{{user_input_text}}'

**Processed Text for Conversion:** '{{processed_text}}'

**Sign Language Display:** The images above represent the sign language for each character in the processed text, demonstrating the conversion from the input text to a visual sequence of signs.

### Sign Language Conversion Summary

**Original Input Text:** '{{user_input_text}}'

**Processed Text for Conversion:** '{{processed_text}}'

**Sign Language Display:** The images above represent the sign language for each character in the processed text, demonstrating the conversion from the input text to a visual sequence of signs.

## Final Task

### Subtask:
Provide a summary of the text-to-sign language conversion, including the input text and the displayed sign language representation.

## Summary:

### Q&A
The task asked for a summary of the text-to-sign language conversion, including the input text and the displayed sign language representation.
*   **Original Input Text:** The example input used was 'ishita'.
*   **Processed Text for Conversion:** The input 'ishita' was processed to 'ISHITA'.
*   **Sign Language Display:** The corresponding sign language images for each character in 'ISHITA' were displayed sequentially.

### Data Analysis Key Findings
*   A comprehensive `char_to_sign_map` was successfully created by combining images from the "American Sign Language Digit dataset" and the "Indian Sign Language (ISL)" dataset.
*   The mapping contains 36 unique characters/digits (0-9 and A-Z), with each associated image resized to a uniform 32x32 pixels and converted to RGB format.
*   User text input is automatically converted to uppercase and filtered to include only characters available in the `char_to_sign_map`. For example, an input of 'ishita' was processed to 'ISHITA'.
*   The system successfully generated and displayed a sequence of sign language images corresponding to the processed text. Each character in the processed text was represented by its respective sign language image.

### Insights or Next Steps
*   The current conversion system effectively demonstrates a foundational text-to-sign language capability, providing a clear visual representation for alphanumeric input.
*   Future enhancements could include implementing more sophisticated handling for characters not present in the mapping (e.g., punctuation, special characters), or exploring animation techniques to create a more dynamic and fluid sign language interpretation.
"""